# Fields with ** must be set! (If the category is enabled)

# Sends messages from Minecraft to Discord and vice versa
discord:
  enabled: false
  #** Token of Discord BOT
  token: "thisIsNotAToken"
  #** The channel ID on which the messages are to be sent or read
  channel: 1234567890987654321
  # If available messages get send over the defined webhook
  webhook-url: "https://discord.com/api/webhooks/id/token"
  # Messages from the Server will have this image (Player Join, Quit, Advancement, Death)
  server-image: "https://cikles.de/minecraft/plugins/Ink/discord_rcp_server.png"

messages:
  player-join: "&a[+] &r%player%"
  player-quit: "&c[-] &r%player%"
  # REQUIRED for discord-chat synchronisation
  # %sourceDisplayName% or %source%
  chat: "%source%: &7%message%"

home:
  enabled: false
  # Time to teleport (in seconds)
  timeout: 10
  # Time between teleports (in minutes)
  cooldown: 30
  # How many Homes per player
  amount: 10

shop:
  enabled: false
  ancient-tomes: [
    minecraft:feather_falling,
    minecraft:thorns,
    minecraft:sharpness,
    minecraft:smite,
    minecraft:bane_of_arthropods,
    minecraft:knockback,
    minecraft:fire_aspect,
    minecraft:looting,
    minecraft:sweeping_edge,
    minecraft:efficiency,
    minecraft:unbreaking,
    minecraft:fortune,
    minecraft:power,
    minecraft:punch,
    minecraft:luck_of_the_sea,
    minecraft:lure ]

enchantments:
  # WARNING: Only disables the events, not the enchantment. They will be still listed in /enchant
  enabled: false
  # Don't drop items they are transferred into the Inventory of the player who broke the Block.
  telekinesis: true
  tree_chopper: true
  vein: true
  oracle: true

mob-griefing: # Set to disable if you want to prevent/disable the damage
  # Damage by Creeper Explosions
  creeper-explosions: true
  # Fire charges wich are shoot by a Ghast
  ghast-explosions: true
  # Block Pickup by Enderman
  enderman: true

# If a player dies, the inventory contents will not drop, instead there will be a "Grave"
graves: false